language: cpp
compiler: gcc
dist: xenial

before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" \
    | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install libdlib-dev libopenblas-dev -y
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - sh .travis-deploy.sh