language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++14
  - echo "deb http://ru.archive.ubuntu.com/ubuntu/ cosmic main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update

install:
  # C++14
  - sudo apt-get install g++-6 libboost1.67-all-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - sh .travis-deploy.sh
