addons:
  apt:
    packages:
      - doxygen
      - graphviz
language: cpp
compiler: gcc
dist: xenial

script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen

deploy:
- provider: script
  skip_cleanup: true
  script:
  - sh .travis-deploy.sh

- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: html
  on:
    branch: master
