language: cpp
compiler: gcc
dist: xenial

before_script:
- sudo apt-get install libboost-test-dev python3-pip -y
- pip3 install setuptools
- pip3 install wheel
- pip3 install conan
- conan install .
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - sh .travis-deploy.sh
