language: cpp
compiler: gcc
dist: xenial

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - sh .travis-deploy.sh
