language: cpp
compiler: gcc
dist: xenial

before_script:
  - sudo apt-get update
  - sudo apt-get install python3-pip -y
  - pip3 install setuptools
  - pip3 install wheel
  - pip3 install conan
  - conan remote add omaralvarez https://api.bintray.com/conan/omaralvarez/public-conan
  - conan install . -s build_type=Release --build=missing
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - sh .travis-deploy.sh